# Site settings
title: Prem
email: pmuruges(at)uncc(dot)edu
description: > # this means to ignore newlines until "baseurl:"
  Stalk me everywhere possible, you will get something useful.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://iamprem.github.com" # the base hostname & protocol for your site
twitter_username: i4mpr3m
github_username:  iamprem
linkedin_username: iamprem
exclude: ['README.md'] #Ignore these files by jekyll, we can also add folder be seperating by commas
# Build settings
# markdown: redcarpet
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
markdown: kramdown
#timezone: Greenwich #Time zone issue in jekyll issue#1069 on github.com/jekyll
kramdown:
 input: GFM
